FrontEnd/src/FrontEnd/Handlers/ApiProxyMiddleware.cs
FrontEnd/src/FrontEnd/Properties/launchSettings.json
FrontEnd/src/FrontEnd/Startup.cs
FrontEnd/src/FrontEnd/appsettings.json
Server/src/HETSAPI/Properties/launchSettings.json

HETS-19 - Friendlier response for when the API proxy can't connect to the API server.

---

Client/package.json
Client/src/js/api.js
Client/src/js/views/Equipment.jsx
Client/src/sass/views/all.scss
Client/src/sass/views/equipment-list.scss

Update license in package.json

HETS-57 Fix styling for equipment search.

---

Client/server/main.js
Client/src/js/api.js
Client/src/js/app.jsx
Client/src/js/reducers/lookups.js
Client/src/js/reducers/models.js
Client/src/js/reducers/search.js
Client/src/js/reducers/ui.js
Client/src/js/reducers/user.js
Client/src/js/reducers/version.js
Client/src/js/views/Equipment.jsx
Client/src/js/views/EquipmentDetail.jsx
Client/src/js/views/OwnersDetail.jsx
Client/src/sass/views/all.scss
Client/src/sass/views/owners.scss

Initial commit for Equipment Details and Owner Details screens

HETS-58 Equipment View Screen

---

Client/src/js/api.js
Client/src/js/components/DropdownControl.jsx
Client/src/js/components/EditDialog.jsx
Client/src/js/components/FormInputControl.jsx
Client/src/js/constants.js
Client/src/js/views/Equipment.jsx
Client/src/js/views/EquipmentDetail.jsx
Client/src/js/views/dialogs/EquipmentEditDialog.jsx
Client/src/js/views/dialogs/SeniorityEditDialog.jsx
Client/src/sass/components/all.scss
Client/src/sass/components/dropdown-control.scss
Client/src/sass/components/edit-dialog.scss
Client/src/sass/views/equipment-list.scss

* Add Equipment edit dialog
* Add Seniority edit dialog
* Port common components from School Bus

HETS-58 Add edit dialogs

---

Client/Dockerfile
Client/gulpfile.js
Client/package.json
Client/src/html/index.hbs
Client/src/html/partials/footer.hbs
Client/src/js/init.js
Client/src/js/utils/shims.js

* Shims missing libs for IE 11
* Turn off compatibility mode
* Remove stale folder
* Update Dockerfile to pass commit number to the Version screen

HETS-76 Add JS Shims for IE 11 Compatibility

---

Client/src/js/api.js
Client/src/js/views/Equipment.jsx
Client/src/js/views/EquipmentDetail.jsx
Client/src/js/views/Owners.jsx
Client/src/js/views/OwnersDetail.jsx
Client/src/js/views/dialogs/EquipmentEditDialog.jsx
Client/src/js/views/dialogs/SeniorityEditDialog.jsx

HETS-109 Create view model for Equipment
HETS-120 HETS Data model updates based on adding projects, request screen JIRAs
HETS-129 Extend the HETS data model to support Rental Agreements

HETS-108 Add missing properties to Owner, Equipment models

---

Client/src/js/views/dialogs/RentalRequestsAddDialog.jsx

HETS-207 "Promise is undefined" error logged in IE when trying to add new rental request

HETS-206 Add Rental Request - Count

---

Client/src/js/api.js
Client/src/js/views/RentalRequestsDetail.jsx
Client/src/js/views/dialogs/RentalRequestsEditDialog.jsx
Client/src/sass/views/rental-requests.scss

HETS-188 Rental Request Edit

---

Client/src/js/api.js
Client/src/js/app.jsx
Client/src/js/views/ProjectsDetail.jsx
Client/src/sass/views/projects.scss

- Add, remove, update a contact from project
- Make a contact primary

HETS-184 - Added project contact functionality

---

Server/src/HETSAPI/Controllers/EquipmentController.cs
Server/src/HETSAPI/Controllers/OwnerController.cs
Server/src/HETSAPI/Controllers/ProjectController.cs
Server/src/HETSAPI/Controllers/RentalRequestController.cs
Server/src/HETSAPI/Helpers/CsvArrayBinder.cs
Server/src/HETSAPI/Services.Impl/EquipmentService.cs
Server/src/HETSAPI/Services.Impl/OwnerService.cs
Server/src/HETSAPI/Services.Impl/ProjectService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/Services/EquipmentService.cs
Server/src/HETSAPI/Services/OwnerService.cs
Server/src/HETSAPI/Services/ProjectService.cs
Server/src/HETSAPI/Services/RentalRequestService.cs

Multiselect search parameters fixed for the following search pages:
- Owners
- Equipment
- Requests
- Projects

HETS-313 Multiselect search parameters enabled

---

Client/src/js/views/Equipment.jsx
Client/src/js/views/Owners.jsx
Client/src/sass/views/owners.scss
Server/src/HETSAPI/Services.Impl/EquipmentService.cs
Server/src/HETSAPI/Services.Impl/OwnerService.cs

Changes include:
- HETS-314 - Owner and equipment status dropdown	
- HETS 315 - Owner dropdown (all) option
- HETS-317 - Move verify button up to header

HETS-316 - Owner and Equipment Search Bugfixes

---

Client/src/js/views/Equipment.jsx
Client/src/js/views/Owners.jsx
Client/src/js/views/Projects.jsx
Client/src/js/views/RentalRequests.jsx
Server/src/HETSAPI/IDbAppContextExtensions.cs
Server/src/HETSAPI/Services.Impl/EquipmentService.cs
Server/src/HETSAPI/Services.Impl/OwnerService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs

This pull request includes bugfixes for various search issues including:
- HETS-326 - Restrict search results by current user district
- HETS-314 - Status drop downs filter search results
- HETS-316 - Add 'all' option to search dropdown controls
- HETS-280 - Hired filter enabled for owner and equipment search

HETS-316 - Various Search Issues

---

Server/src/HETSAPI/Authorization/Import/BCBidImport.cs
Server/src/HETSAPI/Authorization/Import/ImportLocalArea.cs
Server/src/HETSAPI/Authorization/Import/ImportRegion.cs
Server/src/HETSAPI/Authorization/Import/ImportServiceArea.cs
Server/src/HETSAPI/Authorization/Import/ImportUser.cs
Server/src/HETSAPI/Authorization/Import/ImportUtility.cs
Server/src/HETSAPI/Authorization/Import/Mapping.txt

HETS-286 Correct Root directory name

HETS-286 Correct Root directory name

---

Client/src/js/views/RentalAgreementsDetail.jsx
PDF/src/PDF.Server/Templates/rental_agreement.mustache
Server/src/HETSAPI/Services.Impl/RentalAgreementService.cs

Configurations made to the front-end application and API server to allow for the generation and download of rental agreement PDF files.

HETS-311 - Connect Rental Agreement PDF Printing

---

Client/src/js/components/Favourites.jsx
Client/src/js/views/Equipment.jsx
Client/src/js/views/Owners.jsx
Client/src/js/views/Projects.jsx
Client/src/js/views/RentalRequests.jsx
Client/src/js/views/Users.jsx
Client/src/sass/components/all.scss
Client/src/sass/components/favourites.scss
Client/src/sass/components/form-input-control.scss
Client/src/sass/views/equipment-list.scss
Client/src/sass/views/owners.scss
Client/src/sass/views/projects.scss
Client/src/sass/views/rental-requests.scss
Client/src/sass/views/users.scss

- Fixed - The default date search should be "All"
- Fixed - Rental Request favourites not saving
- Changed 'Faves' to Favourites
- Added default placeholders across the views to act as labels
- Set input form control margins to match standard search control margins

HETS-288 - Front-end - Various Search Screen Issues

---

Server/src/HETSAPI/Authorization/Import/BCBidImport.cs
Server/src/HETSAPI/Authorization/Import/Equip.cs
Server/src/HETSAPI/Authorization/Import/ImportBlock.cs
Server/src/HETSAPI/Authorization/Import/ImportCity.cs
Server/src/HETSAPI/Authorization/Import/ImportDisEquipType.cs
Server/src/HETSAPI/Authorization/Import/ImportDistrict.cs
Server/src/HETSAPI/Authorization/Import/ImportDistrictEquipmentType.cs
Server/src/HETSAPI/Authorization/Import/ImportDumpTruck.cs
Server/src/HETSAPI/Authorization/Import/ImportEquip.cs
Server/src/HETSAPI/Authorization/Import/ImportEquipAttach.cs
Server/src/HETSAPI/Authorization/Import/ImportEquipUsage.cs
Server/src/HETSAPI/Authorization/Import/ImportEquipmentType.cs
Server/src/HETSAPI/Authorization/Import/ImportLocalArea.cs
Server/src/HETSAPI/Authorization/Import/ImportOwner.cs
Server/src/HETSAPI/Authorization/Import/ImportProject.cs
Server/src/HETSAPI/Authorization/Import/ImportRegion.cs
Server/src/HETSAPI/Authorization/Import/ImportRotation.cs
Server/src/HETSAPI/Authorization/Import/ImportServiceArea.cs
Server/src/HETSAPI/Authorization/Import/ImportUser.cs
Server/src/HETSAPI/Authorization/Import/ImportUtility.cs
Server/src/HETSAPI/Authorization/Import/Mapping.txt

HETS-365  District_Equipment_TYPE data input
HETS-338  District_Equipment_TYPE data input, Restart data import from where it stopped

HETS-365  District_Equipment_TYPE data input

---

Server/src/HETSAPI/Authorization/Import/BCBidImport.cs
Server/src/HETSAPI/Authorization/Import/ImportBlock.cs
Server/src/HETSAPI/Authorization/Import/ImportCity.cs
Server/src/HETSAPI/Authorization/Import/ImportDisEquipType.cs
Server/src/HETSAPI/Authorization/Import/ImportDistrict.cs
Server/src/HETSAPI/Authorization/Import/ImportDistrictEquipmentType.cs
Server/src/HETSAPI/Authorization/Import/ImportDumpTruck.cs
Server/src/HETSAPI/Authorization/Import/ImportEquip.cs
Server/src/HETSAPI/Authorization/Import/ImportEquipAttach.cs
Server/src/HETSAPI/Authorization/Import/ImportEquipUsage.cs
Server/src/HETSAPI/Authorization/Import/ImportEquipmentType.cs
Server/src/HETSAPI/Authorization/Import/ImportLocalArea.cs
Server/src/HETSAPI/Authorization/Import/ImportOwner.cs
Server/src/HETSAPI/Authorization/Import/ImportProject.cs
Server/src/HETSAPI/Authorization/Import/ImportRegion.cs
Server/src/HETSAPI/Authorization/Import/ImportRotation.cs
Server/src/HETSAPI/Authorization/Import/ImportServiceArea.cs
Server/src/HETSAPI/Authorization/Import/ImportUser.cs
Server/src/HETSAPI/Authorization/Import/ImportUtility.cs
Server/src/HETSAPI/Services.Impl/AdminService.cs

Hangfire has a problem in our case. It creates multiple worked process which interfere with each other for importing data. Use progressive import, we try manual import if disrupted.

HETS-286 Try without Hangfire for progressive importing

---

Server/src/HETSAPI/Authorization/Import/BCBidImport.cs
Server/src/HETSAPI/Authorization/Import/ImportUtility.cs

HETS-286 Move InsertSystemUser from BCBidImport.cs to ImportUtility.cs for code clarity

HETS-286  Move InsertSystemUser from BCBidImport.cs to ImportUtility.cs for code clarity

---

Server/src/HETSAPI/Controllers/AuthenticationController.cs
Server/src/HETSAPI/Views/Home/Index.cshtml

Fix the local "dev" user access functionality

HETS-402 - Unable to access Dev environment with a token to load data

---

Server/src/HETSAPI/Authentication/SiteminderAuthenticationHandler.cs
Server/src/HETSAPI/Controllers/GroupController.cs
Server/src/HETSAPI/Mappings/MappingExtensions.cs
Server/src/HETSAPI/Services.Impl/AdminService.cs
Server/src/HETSAPI/Services.Impl/GroupService.cs
Server/src/HETSAPI/Services/GroupService.cs

Testing modification to Get Groups functionality that is causing a login failure

HETS-407 - Error logging into HETS using SiteMinder (specific accounts only)

---

Server/src/HETSAPI/Controllers/RentalRequestController.cs
Server/src/HETSAPI/Mappings/MappingExtensions.cs
Server/src/HETSAPI/Models/SeniorityListExtensions.cs
Server/src/HETSAPI/Services.Impl/EquipmentService.cs
Server/src/HETSAPI/Services.Impl/ProjectService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/Services/RentalRequestService.cs
Server/src/HETSAPI/ViewModels/EquipmentViewModel.cs
Server/src/HETSAPI/Views/Home/Index.cshtml

HETS-431 - Fix sort order on the Equipment Results Screen - Seniority List
HETS-432 - Projects - Clerks should only be able to see their own district
HETS-165 - Create Rental Request Rotation List API (wip)

HETS-165 - Create Rental Request Rotation List API (wip

---

Server/src/HETSAPI/Controllers/RentalRequestController.cs
Server/src/HETSAPI/Mappings/MappingExtensions.cs
Server/src/HETSAPI/Services.Impl/EquipmentService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/Services.Impl/UserService.cs
Server/src/HETSAPI/Services/RentalRequestService.cs
Server/src/HETSAPI/ViewModels/HomeViewModel.cs
Server/src/HETSAPI/ViewModels/RentalRequestViewModel.cs
Server/src/HETSAPI/ViewModels/RoleViewModel.cs

HETS-433 - User Search - Default search is not returning any records
HETS-431 - Fix sort order on the Equipment Results Screen - Seniority List
HETS-165 - Create Rental Request Rotation List API (wip)

HETS-165 - Create Rental Request Rotation List API (wip)

---

Server/src/HETSAPI/Mappings/MappingExtensions.cs
Server/src/HETSAPI/Models/Attachment.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/Startup.cs
Server/src/HETSAPI/ViewModels/RentalRequestViewModel.cs
Server/src/HETSAPI/appsettings.json

HETS-437 - Rental Request List - remove any pieces of equipment that are active on a contract
HETS-434 - Rental Request - Lock list when in use, correct order of hiring (wip)

HETS-437 - Rental Request List - remove any pieces of equipment that are active on a contract

---

Server/src/HETSAPI/Controllers/RentalRequestController.cs
Server/src/HETSAPI/Models/SeniorityListExtensions.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/Services/RentalRequestService.cs

HETS-437 - Rental Request List - remove any pieces of equipment that are active on a contract
HETS-434 - Rental Request - Lock list when in use, correct order of hiring

HETS-434 - Rental Request - Lock list when in use, correct order of hiring

---

Server/src/HETSAPI/Controllers/ProjectController.cs
Server/src/HETSAPI/Models/RentalRequest.cs
Server/src/HETSAPI/Services.Impl/ProjectService.cs
Server/src/HETSAPI/Services/ProjectService.cs

Added new endpoint to return Rental Agreements (equipment) associated with a project

HETS-436 - Time Entry - save the week and number of hours to db

---

Server/src/HETSAPI/Controllers/ProjectController.cs
Server/src/HETSAPI/Services.Impl/ProjectService.cs
Server/src/HETSAPI/Services/ProjectService.cs

Added new Project services to manage time records

HETS-341 - Time Entry Screen for hired equipment - Back End

---

Server/src/HETSAPI/Mappings/MappingExtensions.cs
Server/src/HETSAPI/Models.Extensions/Equipment.cs
Server/src/HETSAPI/Models/SeniorityListExtensions.cs
Server/src/HETSAPI/Services.Impl/EquipmentService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestRotationListService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/ViewModels/EquipmentViewModel.cs
Server/src/HETSAPI/Views/Home/Index.cshtml

HETS-440 - Hire rotation list - issues with the list displayed on the screen
HETS-438 - The rotation list data is not retrieving the equipment attachments
Improved performance of the seniority recalculation process
Cleaned up default values when creating new equipment

HETS-440 - Hire rotation list - issues with the list displayed on the screen

---

Server/src/HETSAPI/Controllers/ProjectController.cs
Server/src/HETSAPI/Services.Impl/ProjectService.cs
Server/src/HETSAPI/Services/ProjectService.cs

HETS-309 - Project Edit - Contacts Pane - Make Primary not working
Modified the project create contact api to accept a primary indicator and make the new contact primary.

HETS-309 - Project Edit - Contacts Pane - Make Primary not working

---

Jenkins/frontend/Jenkinsfile

- Conditionally build the client application before wrapping it in the frontend proxy server.

Fix client build issue.

---

Server/src/HETSAPI/Services.Impl/RentalRequestService.cs

Create a new Rental Agreement when a piece of equipment is Hired off the Roation List

HETS-211 - Extend or End Hire a Piece of Equipment

---

Server/src/HETSAPI/Services.Impl/ProjectService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs

HETS-419 Additional audit fields
Fixed build error in roation list service
Update the Project Contacts Endpoint to update as well as create contacts

HETS-419 Additional audit fields

---

Server/src/HETSAPI/Controllers/RentalAgreementController.cs
Server/src/HETSAPI/Services.Impl/RentalAgreementService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/Services/RentalAgreementService.cs

HETS-342 - Mark a rented piece of equipment as no longer hired
New service to release a piece of equipment (mark agreement as Complete)
New Time Record services for a rental agreement

HETS-342 - Mark a rented piece of equipment as no longer hired

---

Server/src/HETSAPI/Controllers/EquipmentController.cs
Server/src/HETSAPI/Controllers/OwnerController.cs
Server/src/HETSAPI/Controllers/ProjectController.cs
Server/src/HETSAPI/Controllers/RentalRequestController.cs
Server/src/HETSAPI/Services.Impl/EquipmentService.cs
Server/src/HETSAPI/Services.Impl/OwnerService.cs
Server/src/HETSAPI/Services.Impl/ProjectService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/Services/EquipmentService.cs
Server/src/HETSAPI/Services/OwnerService.cs
Server/src/HETSAPI/Services/RentalRequestService.cs

HETS-344 - Add Notes Capability
Added notes for Project, Owner, Equipment and RentalRequest

HETS-344 - Add Notes Capability

---

Server/src/HETSAPI/Controllers/AttachmentUploadController.cs
Server/src/HETSAPI/Models.Extensions/Equipment.cs
Server/src/HETSAPI/Models/Attachment.cs
Server/src/HETSAPI/Models/SeniorityListExtensions.cs

Fixed 500 error uploading attachments for Equipment
Added MimeType and Type to db on all document uploads

Fixed 500 error uploading attachments for Equipment

---

Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/appsettings.json

HETS-475 - Rotation List - Placing released equipment back into the list in the right place - Normal hire
HETS-477 - Rotation List - Put equipment back on rotation list upon release - Forced hire

HETS-475 - Rotation List - Placing released equipment back into the list in the right place - Normal hire

---

Server/src/HETSAPI/Services.Impl/EquipmentService.cs
Server/src/HETSAPI/appsettings.json

Removed sort on equipment search (causing an error du to bad data)
Fixed configuration in server to call new PDF service

Fixed configuration in server to call new PDF service

---

Client/src/js/utils/http.js
PDF/src/PDF.Server/Controllers/PDFController.cs
Server/src/HETSAPI/Services.Impl/RentalAgreementService.cs

Increased UI timeout on call to Pdf Service
Added additional logging to Agreement generation to assist in debugging

Added additional logging to Agreement generation to assist in debugging

---

Server/src/HETSAPI/Services.Impl/RentalRequestService.cs

HETS-497 - Rotation List giving 500 error after you pull them a certain number of times
HETS-485 - Rental agreement - Move equipment to bottom If the response is "No"

New Rotation list defects

---

Client/init.js
Server/src/HETSAPI/Controllers/ConditionTypeController.cs
Server/src/HETSAPI/Controllers/DistrictEquipmentTypeController.cs
Server/src/HETSAPI/Migrations/20180219212805_HETS-354-1.Designer.cs
Server/src/HETSAPI/Migrations/20180219212805_HETS-354-1.cs
Server/src/HETSAPI/Models/ConditionType.cs
Server/src/HETSAPI/Services.Impl/ConditionTypeService.cs
Server/src/HETSAPI/Services.Impl/DistrictEquipmentTypeService.cs
Server/src/HETSAPI/Services/ConditionTypeService.cs
Server/src/HETSAPI/Services/DistrictEquipmentTypeService.cs
Server/src/HETSAPI/appsettings.json

Modify ConditionTypes to be District specific and create endpoints for editing

HETS-354 - Edit HETS Reference Data

---

Server/src/HETSAPI/Models.Extensions/Permission.cs
Server/src/HETSAPI/Services.Impl/EquipmentService.cs

Ensure the correct data is returned for the Rental Agreement cloning
Added new BCeID Busines Login Permission

Ensure the correct data is returned for the Rental Agreement cloning

---

HETS.sln.DotSettings.user
Server/src/HETSAPI/Controllers/ConditionTypeController.cs
Server/src/HETSAPI/Controllers/TimeRecordController.cs
Server/src/HETSAPI/Models.Extensions/Equipment.cs
Server/src/HETSAPI/Services.Impl/ProjectService.cs
Server/src/HETSAPI/Services.Impl/RentalAgreementService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/Services/RentalRequestService.cs

HETS-553 - Equipment - Seniority, incorrect Block assignment for Dump trucks
Fixed Project Number Search
HETS-537 - Equipment - Fields in the seniority section
Fixed the Hours YTD calculation
HETS-512 - Clone Agreemeent - Paul items

Fixed backend defects

---

Server/src/HETSAPI/Import/ImportOwner.cs
Server/src/HETSAPI/Import/ImportProject.cs

HETS-575 - make Owner Code unique
HETS-576 - Set Project Status during import

HETS-575  HETS-576 Data import improvements

---

Server/src/HETSAPI/Mappings/MappingExtensions.cs
Server/src/HETSAPI/Models/History.cs
Server/src/HETSAPI/Services.Impl/EquipmentService.cs
Server/src/HETSAPI/Services.Impl/OwnerService.cs
Server/src/HETSAPI/Services.Impl/ProjectService.cs
Server/src/HETSAPI/Services.Impl/RentalRequestService.cs
Server/src/HETSAPI/ViewModels/RentalAgreementPdfViewModel.cs

HETS-584 - Owner History - records for each event always show last user to make change to history
HETS-585 - Return complete history record whenever updating history
HETS-583 - Owner History - records for each event always show last user to make change to history

Fixed History Record Creation and Response APIs

---

Jenkins/zap/Jenkinsfile

By creating the pod in this way, we do not have to configure it Jenkins, making the set up a bit more "code-only"

Create the owasp-zap node dynamically

---

Jenkins/sonarqube/Jenkinsfile

This moves the system towards a "code-only" set up instead of having to configure Jenkins.

Dynamically generate node sonarrunner

---

Server/src/HETSAPI/Controllers/AdminController.cs
Server/src/HETSAPI/Import/ImportOwner.cs
Server/src/HETSAPI/Import/ImportUser.cs
Server/src/HETSAPI/Import/ImportUtility.cs
Server/src/HETSAPI/Services.Impl/AdminService.cs
Server/src/HETSAPI/Services/AdminService.cs

HETS-646 - Test/prod data missing parts of contact number
HETS-648 - Data import - Company name is not coming in correctly

Fix data import issues (Company Name and phone number format)

---

Server/src/HETSAPI/Import/BCBidImport.cs
Server/src/HETSAPI/Import/ImportDistrictEquipmentType.cs
Server/src/HETSAPI/Models/AuditableEntity.cs
Server/src/HETSAPI/Models/DbAppContext.cs
Server/src/HETSAPI/Models/HetsDbConcurrencyException.cs
Server/src/HETSAPI/Services.Impl/OwnerService.cs

Added a central concurrency error checker and response message
Fixed the audit fields so the concurrency value is pased to the UI
Added obfuscation code for missing equipment type file

Added a central concurrency error checker and response message

---

Common/src/HetsData/Model/HetProject.cs
FrontEnd/src/FrontEnd/appsettings.json
Server/src/HetsApi/Controllers/ProjectController.cs

HETS-678
Error when creating/updating anything

HETS-678 - Error updating a project request

---

Client/src/js/constants.js
Client/src/js/views/Home.jsx
Client/src/js/views/RentalAgreementsDetail.jsx

Blank rental agreements are now only accessible to administrators and a maximum of 3 is enforced.

HETS-825 limit blank rental agreement functionality

---

Client/src/js/api.js
Client/src/js/utils/http.js
Client/src/js/views/dialogs/RentalAgreementsEditDialog.jsx

+ bonus bugfix for blank rental agreements

 HETS-876 prevent error when printing rental agreements

---

Client/src/js/api.js
Client/src/js/views/TimeEntry.jsx
Client/src/js/views/dialogs/RentalAgreementHeaderEditDialog.jsx
Client/src/js/views/dialogs/RentalRequestsAddDialog.jsx
Client/src/js/views/dialogs/TimeEntryDialog.jsx
Common/src/HetsData/Helpers/OwnerHelper.cs
Server/src/HetsApi/Controllers/OwnerController.cs

Revert "display organization name in owner dropdown"
This reverts commit 32579ef65a41da89ee33505f9e34bd49f73bacbb.
Revert "display project number as prefix in project dropdowns"
This reverts commit d602e0744d40298e9f6eb88b662d83b3dab2902d.
Revert "refresh list of projects when adding new time entries"
This reverts commit 8d73adf49c5c153742353cb853ccfd3cdaf79690.

Revert HETS-1021 pushed to wrong branch

---

Client/src/js/api.js
Client/src/js/views/TimeEntry.jsx
Client/src/js/views/dialogs/RentalAgreementHeaderEditDialog.jsx
Client/src/js/views/dialogs/RentalRequestsAddDialog.jsx
Client/src/js/views/dialogs/TimeEntryDialog.jsx
Common/src/HetsData/Helpers/OwnerHelper.cs
Server/src/HetsApi/Controllers/OwnerController.cs

This was previously pushed to the 1.4 branch by mistake.

HETS-1021 add project number and company name to dropdowns

---

Client/.eslintrc.json
Client/src/js/views/BusinessOwner.jsx
Client/src/js/views/DistrictAdmin.jsx
Client/src/js/views/OwnersDetail.jsx
Client/src/js/views/Projects.jsx
Client/src/js/views/ProjectsDetail.jsx
Client/src/js/views/Version.jsx
Client/src/js/views/dialogs/CloneDialog.jsx
Client/src/js/views/dialogs/TimeEntryDialog.jsx
Client/webpack.config.js

Adds a few more eslint rules too.
No longer emits JS when there are eslint warnings or errors. I could not get the build to fail because of lint issues so this is the next best approach.

HETS-1020 - adds cell & fax numbers to contacts

---

Client/package.json

The patch value in the version is required ...

Fixes package.json version

---

Client/src/js/components/PageOrientation.jsx
Client/src/js/views/RentalRequestsDetail.jsx
Client/src/sass/print.scss

Except the rotation list which is forced to be landscape.

HETS-1057 - Allow portrait or landscape in browser printing dialog

---

Client/src/js/views/Version.jsx

HETS-1087 - Fixes printed version page

---

Client/src/js/utils/http.js
Client/src/js/views/EquipmentDetail.jsx
Client/src/js/views/OwnersDetail.jsx
Client/src/js/views/dialogs/ChangeStatusDialog.jsx
Server/src/HetsApi/Controllers/EquipmentController.cs

HETS-1069 - archived equipment status change dialog shows api error

---

Client/src/js/components/Favourites.jsx
Client/src/js/components/FormDialog.jsx
Client/src/sass/gov3.scss

Updates Favourites to use new FormDialog component.

HETS-1101 - creates FormDialog component to replace EditDialog

---

Client/src/js/api.js
Client/src/js/reducers/models.js
Client/src/js/views/EquipmentDetail.jsx
Client/src/js/views/OwnersDetail.jsx
Client/src/js/views/ProjectsDetail.jsx
Client/src/js/views/RentalRequestsDetail.jsx
Client/src/js/views/dialogs/NotesAddDialog.jsx
Client/src/js/views/dialogs/NotesDialog.jsx
Client/src/sass/gov3.scss
Common/src/HetsData/Model/HetNote.cs

Notes are now updated to reflect API's data after each change.

HETS-1148 - Adds note's date to notes dialog.

---

openshift/backup-deploy-config.yaml
rocketchat/README.md

updated rocketchat README
changed backup to use admin account.

1.9.3 updating db backup accounts

---

client/src/js/components/Confirm.jsx
client/src/js/components/DeleteButton.jsx
client/src/js/views/UsersDetail.jsx

UserDetail.js overlays weren't working correctly, so I fixed this. Also fixed some formatting issues when showing user roles.

1.9.3 HETS-1331 overlay Bug fix complete + UserDetail.js UI fix

---

Server/HetsData/Helpers/SeniorityListHelper.cs

This update is for fixing TH-86168.
https://jira.th.gov.bc.ca/browse/TH-86168

Fix TH-86168

---

Server/HetsApi/HetsApi.csproj
Server/HetsApi/appsettings.json

update version to 1.10.4

---

client/src/js/views/dialogs/DocumentsListDialog.jsx

For resolving [TH-86790](https://jira.th.gov.bc.ca/browse/TH-86790), the " in the regular expression could make there is no match found when trying to get the attachment file name.

For resolving TH-86790

---

Server/HetsApi/Controllers/RentalRequestController.cs
Server/HetsApi/HetsApi.csproj
Server/HetsApi/appsettings.json
Server/HetsData/Repositories/RentalRequestRepository.cs

TH-115131: recalculate rotation list order based on LastCalled

TH-115131: recalculate rotation list order based on LastCalled

---

client/src/js/views/OwnersDetail.jsx
client/src/js/views/WcbCglCoverage.jsx
client/src/js/views/dialogs/OwnersPolicyEditDialog.jsx

1.10.12 - TH-119992: Remove the WCB & CGL expiry date

1.10.12 - TH-119992: Remove the WCB & CGL expiry date
